flisol2018/flisol2018/urls.py
from django.contrib import admin
from django.urls import path

#from form.views import ParticipanteCreateView, ParticipanteList
from form.views import participanteCreate, participanteDetalle, lista
urlpatterns = [
    path('admin/', admin.site.urls),
    # formulario de participacion
    path('', participanteCreate, name='registrar-participante'),
    path('par/<slug:slg>/', participanteDetalle, name='participante-detalle'),
    path('par/<slug:slg>/<slug:md>', participanteDetalle, name='participante-detalle'),
    path('p/lista/', lista, name='lista'),
    path('p/lista/<slug:slg>', lista, name='lista_mas'),
]

flisol2018/form/models.py
from django.db import models

# Create your models here.

SEXO_CHOICES = [
    ('Mujer', 'Mujer'),
    ('Hombre', 'Hombre'),
    ('Prefiero no decirlo', 'prefiero no decirlo')
]

GRADO_ACADEMICO_CHOICES = [
    ('Bachiller', 'Bachiller'),
    ('Técnico', 'Técnico'),
    ('Licenciatura', 'Licenciatura'),
    ('Magíster', 'Maǵister'),
    ('Doctor', 'Doctor'),
    ('Prefiero no indicar', '-'),
]

PARTICIPACION_CHOICES = [
    ('Quiero que me ayuden a instalar software libre en mi computadora','Sólo asistir'),
    ('Como expositor con el tema:','Exponer un tema'),
    ('Ayudando en la instalación de software el día del FLISOL o capacitando a otros para ser instaladores', 'Instalador'),
    ('Me gustaría una mesa para hablar de una tematica relacionada al software libre','Mesa de debate'),
    ('Quiero ayudar en la organización y logística del evento','Logística'),
    ('Otro', 'otro')
]

class Participante(models.Model):
    email = models.EmailField(max_length=254,
                              help_text='Registre su correo electrónico')

    nombres = models.CharField(max_length=500)
    apellidos = models.CharField(max_length=500)

    telf = models.CharField(max_length=100,
                            default=" ",
                            help_text="Número de teléfono móvil (opcional)",
                            blank=True)
    
    sexo = models.CharField(max_length=20,
                            default=' ',
                            choices=SEXO_CHOICES)
    grupo = models.CharField(max_length=300,
                             default=' ',
                             help_text="Grupo o asociación a la que pertenece (Pude dejar en blanco)",
                             blank=True)
    grado_academico = models.CharField(max_length=300,
                                       choices=GRADO_ACADEMICO_CHOICES,
                                       default="prefiero no especificar",
                                       help_text="Máximo grado académico alcanzado")

    conoce_el_flisol = models.BooleanField(default=False,
                                        help_text="¿Sabe que es el FLISOL?")
    conoce_el_software_libre = models.BooleanField(default=False,
                                                help_text="¿Conoce el Software Libre?")

    ha_usado_software_libre = models.BooleanField(default=False, help_text="¿Ha usado software libre?")

    tipo_de_participacion = models.CharField(max_length=1000,
                                          default=PARTICIPACION_CHOICES[0],
                                          choices=PARTICIPACION_CHOICES,
                                          help_text="Seleccione la forma en la que desea participar")
    comentarios = models.CharField(max_length=1000,
                                   default=" ",
                                   blank=True,
                                   help_text='Comentarios o sugerencias para la organización del evento')

    def __str__(self):
        r = str(self.id)+":<"+self.email+'> '+self.nombres+' '+self.apellidos + ', tipo:' + str(self.tipo_de_participacion)
        return r

    def get_absolute_url(self):
        return reverse('participante-detalle', kwargs={'pk': self.pk})
    
INSTALADOR_TIPO_SOFTWARE_CHOICES = [
    ("Sistemas Operativos libres para PC","Sistemas Operativos libres para PC"),
    ("Sistemas Operativos libres para Moviles","Sistemas Operativos libres para Moviles"),
    ("Programas libres para diferentes temáticas (favor describir que temáticas o programas en la opción 'Otros')", "Programas libres para diferentes temáticas"),
    ("Otro","Otro")
]

LOGISTICA_TIPO_CHOICES = [
    ("Apoyo logístico en la organización y gestión del evento.","Apoyo logístico en la organización y gestión del evento."),
    ("Difusión en redes sociales","Difusión en redes sociales"),
    ("Difusión en prensa y otros medios de comunicación","Difusión en prensa y otros medios de comunicación"),
    ("Difusión en prensa y otros medios de comunicación","Difusión en prensa y otros medios de comunicación"),
    ("Otro", "Otro")
]

ASISTENTE_SOFTWARE_DESEADO_CHOICES = [
    ("Educativo","Educativo"),
    ("Para Internet","Para Internet"),
    ("Juegos","Juegos"),
    ("Multimadia","Multimedia"),
    ("Accesorios","Accesorios"),
    ("Diseño gráfico","Diseño gráfico"),
    ("Seguridad","Seguridad"),
    ("Oficina", "Oficina"),
    ("Programación","Programación"),
    ("Científico","Científico"),
    ("Otro","Otro")
]
    
class TipoParticipacion(models.Model):
    participante = models.ForeignKey('Participante',
                                     default=1,
                                     on_delete=models.CASCADE)
    tipo = models.CharField(max_length=1000,
                            default=PARTICIPACION_CHOICES[0])

    # expositores
    expositor = models.BooleanField(default=False)
    expositor_software_manejado = models.CharField(max_length=1000,
                                                     help_text="Por favor indica algunos ejemplos del software libre que has manejado (y si gustas algunos ejemplos del uso que le has dado)",
                                                   default=" ",
                                                   blank=True)
    expositor_tema = models.CharField(max_length=500,
                                      help_text="Indica el tema que desea exponer",
                                      default=" ",
                                      blank=True)

    # asistentes
    asistente = models.BooleanField(default=False)
    asistente_software_deseado = models.CharField(max_length=500,
                                                  choices=ASISTENTE_SOFTWARE_DESEADO_CHOICES,
                                                  default=ASISTENTE_SOFTWARE_DESEADO_CHOICES[0])
    asistente_otro_desc = models.CharField(max_length=500,
                                           default=" ",
                                           blank=True)
    
    # para instaladores
    instalador = models.BooleanField(default=False)
    instalador_capacitacion = models.BooleanField(default=True,
                                                  help_text="Requeriré capacitación para para ayudar como instalador")
    instalador_tipo_software = models.CharField(max_length=500,
                                                default=INSTALADOR_TIPO_SOFTWARE_CHOICES[0],
                                                choices=INSTALADOR_TIPO_SOFTWARE_CHOICES,
                                                help_text="Indica el tipo de software que nos podrías ayudar a instalar")

    # para colaboradores en logistica
    logistica = models.BooleanField(default=False)
    logistica_tipo = models.CharField(max_length=500,
                                      choices=LOGISTICA_TIPO_CHOICES)
    logistica_otro_desc = models.CharField(max_length=1000,
                                           default=" ", blank=True)

    # otro tipo de ayuda
    otro = models.BooleanField(default=False)
    otro_desc = models.CharField(max_length=1000,
                                 default=" ")
    
    def __str__(self):
        r = str(self.id) + '(' + str(self.participante.id) + ')' + self.tipo +' : ' 
        r = r + str(self.logistica_tipo) if self.logistica else r
        r = r + str(self.expositor_tema) if self.expositor else r
        r = r + str(self.asistente_software_deseado) if self.asistente else r
        r = r + str(self.instalador_tipo_software) if self.instalador else r
        r = r + str(self.otro_desc) if self.otro else r
        return r

flisol2018/form/forms.py
from django.forms import ModelForm

from form.models import Participante, TipoParticipacion

class ParticipanteForm(ModelForm):
    class Meta:
        model = Participante
        fields = ['email', 'nombres', 'apellidos', 'telf', 'sexo', 'grupo', 'grado_academico', 'conoce_el_flisol', 'conoce_el_software_libre', 'ha_usado_software_libre', 'tipo_de_participacion', 'comentarios']

flisol2018/form/views.py
from django.shortcuts import render
import hashlib

from django.template.response import TemplateResponse
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.utils import timezone
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse, HttpResponseRedirect

from django.http import Http404
from django.shortcuts import render
#from django.core.urlresolvers import reverse

from .models import Participante, TipoParticipacion
from .forms import ParticipanteForm

from flisol2018.settings import SECRET_1

# Create your views here.
def participanteCreate(request):
    if request.method == "GET":
        form = ParticipanteForm()
        return render(request, 'form/participante_form.html', {'form':form})

    if request.method == "POST":
        print (request.POST)
        form = ParticipanteForm(request.POST)
        print(form.is_valid())
        #print('errors:   >>>'+str(form.errors))
        if not form.is_valid():
            return HttpResponse("Error al llenar el formulario")

        participante = form.save()
        print ("PAR",str(participante))

        # creando el tipo de participacion                          
        tipo = TipoParticipacion()
        try:
            tipo.participante = participante
        except Exception as error:
            print ("error al crear tipo", error)
            
        if request.POST.get('tipo_participacion_val') == 'asistente':
            tipo.tipo = 'asistente'
            tipo.asistente = True
            tipo.asistente_software_deseado = request.POST.get('asistente_software_deseado')
        elif request.POST.get('tipo_participacion_val') == 'expositor':
            tipo.tipo = 'expositor'
            tipo.expositor = True
            tipo.expositor_software_manejado = request.POST.get('expositor_software_manejado')
            tipo.expositor_tema = request.POST.get('expositor_tema')
        elif request.POST.get('tipo_participacion_val') == 'logistica':
            tipo.tipo = 'logistica'
            tipo.logistica = True
            tipo.logistica_tipo = request.POST.get('logistica_tipo')
        elif request.POST.get('tipo_participacion_val') == 'instalador':
            tipo.tipo = 'instalador'
            tipo.instalador = True
            if (request.POST.get('instalador_capacitacion') == 'on'):
                tipo.instalador_capacitacion = True
            else:
                tipo.instalador_capacitacion = False
            tipo.instalador_tipo_software = request.POST.get('instalador_tipo_software')
        elif request.POST.get('tipo_participacion_val') == 'mesa':
            tipo.tipo = 'mesa'
        elif request.POST.get('tipo_participacion_val') == 'otro':
            tipo.tipo = 'otro'
            tipo.otro = True
            tipo.otro_desc = request.POST.get('ayuda_otro')
        tipo.save()
        
        ruta = hashlib.sha1(SECRET_1.encode('utf-8')*(participante.id)).hexdigest()
        print (ruta)
        return HttpResponseRedirect('/par/'+ruta)
    #return HttpResponse("hecho?")

def participanteDetalle(request, slg, md=' '):
    # buscando el slug que tenga que ver con la clave
    p_id = -1
    for p in Participante.objects.all():
        test = hashlib.sha1(SECRET_1.encode('utf-8')*p.id).hexdigest()
        if test == slg:
            p_id = p.id
            break;
        
    if p_id <= 0:
        print('no funciona ese', slg)
        raise Http404("No existe ese participante")
    
    try:
        p = Participante.objects.get(pk=p_id)
        t = TipoParticipacion.objects.get(participante=p)
    except Participante.DoesNotExist as e:
        print ('error:', e)
        raise Http404("No existe ese participante")

    return render(request, 'form/participante_detalle.html',
                  {'participante':p,
                   'tipo': t,
                   'mas_detalles': md.count('_')>0
                  })

def lista(request, slg=''):
    if request.method == "GET":
        p = []

        numAsistentes = numExpositores = numLogistica = numMesas = 0
        total = numOtro = 0
        try:
            numInstaladores = TipoParticipacion.objects.filter(tipo='instalador').count()
            numAsistentes = TipoParticipacion.objects.filter(tipo='asistente').count()
            numExpositores = TipoParticipacion.objects.filter(tipo='expositor').count()
            numLogistica = TipoParticipacion.objects.filter(tipo='logistica').count()
            numMesas = TipoParticipacion.objects.filter(tipo='mesa').count()
            numOtro = TipoParticipacion.objects.filter(tipo='otro').count()
            total = TipoParticipacion.objects.all().count()
        except Exception as e:
            print ("error:", e)

        participantes = Participante.objects.all()
        for par in participantes:
            try:
                tipo = TipoParticipacion.objects.get(participante=par)
                slug = hashlib.sha1(SECRET_1.encode('utf-8')*par.id).hexdigest()
                obj = {'p':par, 'tipo': tipo, 'slug': slug}
                p.append(obj)
            except TipoParticipacion.DoesNotExist as e:
                print("error", str(par), str(e))
        return render(request, 'form/participante_lista.html',
                          {'participantes': p ,
                           'mas_detalles': slg.count('_')>0,
                           'expositores': numExpositores,
                           'asistentes': numAsistentes,
                           'logistica': numLogistica,
                           'mesas': numMesas,
                           'instaladores': numInstaladores,
                           'otro': numOtro,
                           'total': total})

flisol2018/form/templates/form/participante_detalle.html
{% extends "base_form.html" %}
{% block content %}
    <h2>Detalles participante registrado</h2>
    <br>
    <b>Nombre:</b> {{ participante.nombres }} {{ participante.apellidos }}
    <br>
    <b>email:</b>
    {% if mas_detalles %}
	<code>{{ participante.email }}</code>
    {% else %}
	<small>registrado</small>
    {% endif %}
    
    <br>
    <b>Telf:</b>
    {% if mas_detalles %}
	<span class="text-muted">{{ participante.telf }}</span>
    {% else %}
	 <small>registrado</small>
    {% endif %}
    <br>
    <b>Grupo:</b> {{ participante.grupo }}
    
    <div><small><b>Sexo:</b> {{ participante.sexo }}</small></div>
    <hr>
    <h3>Modo de participación ({{ tipo.tipo }})</h3>
    </p>
    <p>
	{% if tipo.tipo == "asistente" %}
	    <p>
		<b>Interesado en software </b>{{ tipo.asistente_software_deseado }}
	    </p>
	{% endif %}
	{% if tipo.tipo == "expositor" %}
	    <p>
		<b>Maneja el software </b>{{ tipo.expositor_software_manejado }}
	    </p>
	    <p>
		<b>Desea exponer el Tema:</b> {{ tipo.expositor_tema }}
	    </p>
	{% endif %}
	{% if tipo.tipo == "logistica" %}
	    <p>
		<b>Desea colaborar en </b>{{ tipo.logistica_tipo }}
	    </p>
	{% endif %}
	{% if tipo.tipo == "instalador" %}
	    <p>
		<b>Requiere capacitación como instalador</b>
		{% if tipo.instalador_capacitacion %} SI {% else %} NO {% endif %}
	    </p>
	    <p>
		<b>Puede instalar software para:</b> {{ tipo.instalador_tipo_software }}
	    </p>
	{% endif %}
	{% if tipo.tipo == "otro" %}
	    <p>
		<b>Desea participar en </b>{{ tipo.otro_desc }}
	    </p>
	{% endif %}
    </p>
    <p>
	{% if participante.comentarios != " " %}
	    <b>Ha dejado el comentario:</b>
	    <p>
		{{ participante.comentarios }}
	    </p>
	    
	{% endif %}
    </p>
{% endblock %}

flisol2018/form/templates/form/participante_form.html
{% extends "base_form.html" %}

{% block content %}
    <h1>Formulario de participación</h1>
    <form action="" method="post" style="background-color: #EEE; padding-left: 15px; border-radius: 9px">
	{% csrf_token %}
	<div class="form-group">
	    {{ form.email.label_tag }}
	    <br>
	    {{ form.email }}
	</div>
	<div class="form-group">
	    {{ form.nombres.label_tag }}
	    <br>
	    {{ form.nombres }}
	</div>
	<div class="form-group">
	    {{ form.apellidos.label_tag }}
	    <br>
	    {{ form.apellidos }}
	</div>
	<div class="form-group">
	    {{ form.telf.label_tag }}
	    {{ form.telf }}		<small class="form-text text-muted">{{ form.telf.help_text }}</small>
	</div>
	<div class="form-group">
	    {{ form.sexo.label_tag }}
	    {{ form.sexo }}
	</div>
	<div class="form-group">
	    {{ form.grupo.label_tag }}
	    {{ form.grupo }}
	    <small class="form-text text-muted">{{ form.grupo.help_text }}</small>
	</div>
	<div class="form-group">
	    <label>{{ form.grado_academico.help_text }}</label>
 	    {{ form.grado_academico }}
	</div>
	<div class="form-group">
	    <label>{{ form.conoce_el_flisol.help_text }}</label>
	    <span style="background-color: #BEF395"> &nbsp;&nbsp;&nbsp;{{ form.conoce_el_flisol }}&nbsp;&nbsp;&nbsp;</span>
	</div>
	<div class="form-group">
	    <label>{{ form.conoce_el_software_libre.help_text }}</label>
	    <span style="background-color: #BEF395"> &nbsp;&nbsp;&nbsp;{{ form.conoce_el_software_libre }}&nbsp;&nbsp;&nbsp;</span>
	</div>
	<div class="form-group">
	    <label>{{ form.ha_usado_software_libre.help_text }}</label>
	    <span style="background-color: #BEF395"> &nbsp;&nbsp;&nbsp;{{ form.ha_usado_software_libre }}&nbsp;&nbsp;&nbsp;</span>
	</div>

	<h5>{{ form.tipo_de_participacion.help_text }}</h5>
	<div class="form-group" style="background-color: #F1EFCC; border-radius: 5px; padding: 5px;">
	    {{ form.tipo_de_participacion }}
	    <br><br>

	    <div id="ayuda_asistente"
		 style="visibility: hidden; display: none">
		<!-- asistentes -->
		<p>
		    <strong>¿Qué tipo de software desea que le instalen?</strong>
		    <select id="id_asistente_software_deseado" name="asistente_software_deseado">
			<option value="Sistema Operativo GNU/Linux"> Sistema Operativo GNU/Linux
			</option>
			<option value="Educativo"> Educativo
			</option>
			<option value="Para Internet"> Para Internet
			</option>
			<option value="Juegos"> Juegos
			</option>
			<option value="Multimedia"> Multimedia
			</option>
			<option value="Accesorios"> Accesorios
			</option>
			<option value="Diseño gráfico"> Diseño Gráfico
			</option>
			<option value="Seguridad"> Seguridad
			</option>
			<option value="Oficina"> Oficina
			</option>
			<option value="Programación"> Programación
			</option>
			<option value="Científico"> Científico
			</option>
			<option value="Otro"> Otro
			</option>
		    </select>
		</p>
	    </div>
	    
	    <div id="ayuda_instalador"
		 style="visibility: hidden; display: none">
		<!-- instaladores -->
		<h4 style="color: #9AA17B">Ayudar en instalación de software</h4>
		<p>
		    <strong>¿Requiere capacitación para ayudar como instalador?</strong>
		    <span style="background-color: #E5FF73"> &nbsp;&nbsp;
			<input name="instalador_capacitacion" id="id_instalador_capacitacion" type="checkbox" >
			&nbsp;&nbsp;
		    </span>
		</p>
		<p>
		    <strong>Indique el tipo de software que puede ayudar a instalar</strong>
		    <select id="id_instalador_tipo_software" name="instalador_tipo_software">
			<option value="Sistemas Operativos libres para PC" select="">Sistemas Operativos libres para PC
			</option>
			<option value="Sistemas Operativos libres para Moviles">Sistemas Operativos libres para Moviles
			</option>
			<option value="Programas libres para diferentes temáticas">Programas libres para diferentes temáticas
			</option>
			<option value="Otro">
			    Otro
			</option>
		    </select>
		</p>
	    </div>
	    <!-- Expositores -->
	    <div id="ayuda_expositor"
		 style="">
		<h4 style="color: #9AA17B">Como expositor</h4>
		<strong>Por favor indica algunos ejemplos del software libre que has manejado (y si gustas algunos ejemplos del uso que le has dado)</strong>
		<br>
		<textarea id="id_expositor_software_manejado" name="expositor_software_manejado" rows="2" cols="39"
			  maxlength="500">
		</textarea>
		<br>
		
		<strong>Tema que desea exponer:</strong>
		<br>
		<input id="id_expositor_tema" name="expositor_tema" maxlength="500" size="39">
		
	    </div>
	    <!-- Logistica -->
	    <div id="ayuda_logistica"
		 style="visibility: hidden; display: none">
		<h4 style="color: #9AA17B">Apoyo logístico</h4>
		<strong>Indica el área en que te gustaría colaborar</strong>
		<select id="id_logistica_tipo" name="logistica_tipo">
		    <option value="Apoyo logístico en la organización y gestión del evento">Apoyo logístico en la organización y gestión del evento</option>
		    <option value="Difusión en redes sociales">
			Difusión en redes sociales
		    </option>
		    <option value="Difusión en prensa y otros medios de comunicación">
			Difusión en prensa y otros medios de comunicación
		    </option>
		    <option value="Documentar el día del evento (Fotografías, vídeos, otros)">
			Documentar el día del evento (Fotografías, vídeos, otros)
		    </option>
		    <option value="Otro">
			Otro
		    </option>
		</select>
	    </div>
	    <!-- Otro -->
	    <div id="ayuda_otro"
		 style="visibility: hidden; display: none">
		<strong> ¿De qué otra forma quiere participar? </strong>
		<input id="id_ayuda_otro" maxlength="500" size="39" name="ayuda_otro">
	    </div>

	    <input type="hidden" id="id_tipo_de_participacion_val" name="tipo_participacion_val" value="asistente"/>

	</div>
	<div class="form-group">
	    {{ form.comentarios.help_text }} (opcional)
	    <br>
	    {{ form.comentarios }}
	</div>
	
	<input type="submit" class="btn btn-primary" value="CONFIRMAR">
    </form>

    
    <script>
     let domTipoParticipacion = document.getElementById("id_tipo_de_participacion");
     
     let domAyudaLogistica = document.getElementById("ayuda_logistica");
     let domAyudaInstalador = document.getElementById("ayuda_instalador");
     let domAsistente = document.getElementById("ayuda_asistente");
     let domAyudaExpositor = document.getElementById("ayuda_expositor");
     let domAyudaOtro = document.getElementById("ayuda_otro");
     let domTipoParticipacionVal = document.getElementById("id_tipo_de_participacion_val");
     
     let asistente, mesa, instalador, expositor, logistica, otro = false;

     function actualizarSleccionParticipacion() {
	 OcultarBloques();
	 for (let option of domTipoParticipacion.options) {
	     if (option.selected) {
		 asistente = option.value.startsWith("Quiero que me ayuden")? true: false;
		 expositor = option.value.startsWith("Como expositor")? true: false;
		 instalador = option.value.startsWith("Ayudando en la instala")? true: false;
		 mesa = option.value.startsWith("Me gustaría una mesa")? true: false;
		 logistica = option.value.startsWith("Quiero ayudar en la organización")?true:false;
		 otro = option.value.startsWith("Otro");
		 break;
	     }
	 }
	 console.log("asistente",asistente,"instalador",instalador,'mesa',mesa,'otro',otro, 'logistica', logistica, 'expositor',expositor);
	 if (instalador) {
	     domAyudaInstalador.style.visibility = "visible";
	     domAyudaInstalador.style.display = "block";
	     domTipoParticipacionVal.setAttribute("value", "instalador");
	 }
	 if (logistica) {
	     domAyudaLogistica.style.visibility = "visible";
	     domAyudaLogistica.style.display = "block";
	     domTipoParticipacionVal.setAttribute("value", "logistica");
	 }
	 if (expositor) {
	     domAyudaExpositor.style.visibility = "visible";
	     domAyudaExpositor.style.display = "block";
	     domTipoParticipacionVal.setAttribute("value", "expositor");
	 }
	 if (otro) {
	     domAyudaOtro.style.visibility = "visible";
	     domAyudaOtro.style.display = "block";
	     domTipoParticipacionVal.setAttribute("value", "otro");
	 }
	 if (asistente) {
	     domAsistente.style.visibility = "visible";
	     domAsistente.style.display = "block";
	     domTipoParticipacionVal.setAttribute("value", "asistente");
	     
	 }
	 if (mesa) {
	     domTipoParticipacionVal.setAttribute("value", "mesa");
	 }
     }
     actualizarSleccionParticipacion();
     
     domTipoParticipacion.addEventListener("change", event => {
	 actualizarSleccionParticipacion();
     });

     function OcultarBloques() {
	 domAyudaInstalador.style.visibility = "hidden";
	 domAyudaInstalador.style.display = "none";
	 domAyudaLogistica.style.visibility = "hidden";
	 domAyudaLogistica.style.display = "none";
	 domAyudaExpositor.style.visibility = "hidden";
	 domAyudaExpositor.style.display = "none";
	 domAyudaOtro.style.visibility = "hidden";
	 domAyudaOtro.style.display = "none";
	 domAsistente.style.visible = "hidden";
	 domAsistente.style.display = "none";
     } 
    </script>

{% endblock %}

flisol2018/form/templates/form/participante_lista.html
{% extends "base_form.html" %}
{% block content %}
    <a href="/" class="btn btn-ligth btn-sm">Regístrate</a> | <a class="btn btn-ligth btn-sm" href="#lista">Lista</a>

    <!-- estadisticas -->
    <div>
	<canvas id="canvas1" width="350" height="200"></canvas>
    </div>	
    <script>
     let cx = document.getElementById("canvas1").getContext("2d");
     let ancho = ((parseInt({{ asistentes }})*100)/({{ total }}))*2;
     cx.font="14px Sans";
     cx.fillStyle = "blue";
     cx.fillRect(0, 10, ancho, 25);
     cx.fillText("Asistentes: "+{{ asistentes }}, 210, 25);
     cx.fillStyle = "magenta";
     ancho = ((parseInt({{ instaladores }})*100)/({{ total }}))*2;
     cx.fillRect(0, 40, ancho, 25);
     cx.fillText("Instaladores: "+{{ instaladores }}, 210, 55);
     cx.fillStyle = "#432";
     ancho = ((parseInt({{ expositores }})*100)/({{ total }}))*2;
     cx.fillRect(0, 70, ancho, 25);
     cx.fillText("Expositores: "+{{ expositores }}, 210, 85);
     cx.fillStyle = "green";
     ancho = ((parseInt({{ logistica }})*100)/({{ total }}))*2;
     cx.fillRect(0, 100, ancho, 25);
     cx.fillText("Logística: "+{{ logistica }}, 210, 115);
     cx.fillStyle = "red";
     ancho = ((parseInt({{ mesas }})*100)/({{ total }}))*2;
     cx.fillRect(0, 130, ancho, 25);
     cx.fillText("Mesas de debate: "+{{ mesas }}, 210, 145);
     cx.fillStyle = "#559";
     ancho = ((parseInt({{ otro }})*100)/({{ total }}))*2;
     cx.fillRect(0, 160, ancho, 25);
     cx.fillText("Otros: "+{{ otro }}, 210, 175);
     
    </script>
    <h3 id="lista">Lista rápida de participantes</h3>

    {% for p in participantes reversed %}
	<hr>
	<b>Nombre:</b> <a href="/par/{{ p.slug }}/">{{ p.p.nombres }} {{ p.p.apellidos }}</a>
	&nbsp;&nbsp;&nbsp;<b>Grupo:</b> {{ p.p.grupo }}
	<br>
	<b>Quiere participar como:</b> <code>{{ p.tipo.tipo }}</code>
	<br>
	{% if mas_detalles %}
	    <b>Email:</b> {{ p.p.email }}
	    <br>
	    <b>Telf:</b> {{ p.p.telf }}
	{% endif %}
	<br>
	{% if p.tipo.tipo == "asistente" %}
	    <b>Interesado en software </b> {{ p.tipo.asistente_software_deseado }}
		<br>
	{% endif %}
	{% if p.tipo.tipo == "expositor" %}
	    <b>Maneja el software </b>{{ p.tipo.expositor_software_manejado }}
		<br>
		<b>Desea exponer el Tema</b> <big><i>{{ p.tipo.expositor_tema }}</i></big>
		<br>
	{% endif %}
	{% if p.tipo.tipo == "logistica" %}
	    <p>
		<b>Desea colaborar en </b>{{ p.tipo.logistica_tipo }}
	    </p>
	{% endif %}
	{% if p.tipo.tipo == "instalador" %}
		<b>Requiere capacitación como instalador</b>
		{% if p.tipo.instalador_capacitacion %} SI {% else %} NO {% endif %}
		<br>
		<b>Puede instalar software para:</b> {{ p.tipo.instalador_tipo_software }}
		<br>
	{% endif %}
	{% if p.tipo.tipo == "otro" %}
		<b>Desea participar en </b>{{ p.tipo.otro_desc }}
		<br>
	{% endif %}
    {% endfor %}
{% endblock %}